server.port: 8765

eureka:
  client:
    service-url: 
      defaultZone:  http://localhost:8761/eureka/
      
#fegin自带段录取 D版之后本需要配置打开 feign.hystrix.enabled=true
#F版本需要打开啦
feign: 
 hystrix: 
  enabled: true
     
spring: 
  application:
    name: service-feign
    
